version: '3.8'

services:
  web_ui_prod:
    image: ghcr.io/lifelong-learning-assisttant/web_ui_service:v001
    ports:
      - "8150:8150"
    networks:
      - internal_network
      - rag_network
      - test_generator_network
    environment:
      - PYTHONUNBUFFERED=1
      - AGENT_SERVICE_URL=http://agent_service:8250
    volumes:
      - ./app_settings-prod.json:/app/app_settings.json:ro
    command: uv run python web_ui.py --settings app_settings.json

networks:
  internal_network:
    driver: bridge
    name: web_ui_internal_network
  rag_network:
    external: true
    name: rag_rag_network
  test_generator_network:
    external: true
    name: llm_tester_default